apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Extend the base configuration
resources:
  - ../../base

# Specific namespace for dev
namespace: ergo-dev

# Override tags for development (e.g., using a branch-specific tag)
images:
  - name: ghcr.io/tdk-soft/ergo-maffo-cloud-native/ergo-site
    newTag: dev-latest

# Override or add development specific variables
configMapGenerator:
  - name: ergo-config
    behavior: merge
    literals:
      - DEBUG_MODE=true
      - FEATURE_FLAG_BETA=true

# Add a prefix to all resources to avoid collision in shared clusters
namePrefix: dev-