apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: ergo-prod
namePrefix: prod-

images:
  - name: ghcr.io/tdk-soft/ergo-maffo-cloud-native/ergo-site
    newTag: v1.0.0

patches:
  
  - path: patches/deployment-patch.yaml
    target:
      kind: Deployment
      name: ergo-site
  
  
  - path: patches/ingress-host-patch.yaml
    target:
      kind: Ingress
      name: ergo-ingress

configMapGenerator:
  - name: ergo-config
    behavior: merge
    envs:
      - configs/prod-config.env

secretGenerator:
  - name: ergo-secrets
    behavior: merge
    envs:
      - configs/prod-secret.env