name: CD - Production Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      # Render the manifest
      - name: Build Kustomize Manifest
        run: |
          cd k8s/overlays/production
          kustomize edit set image ghcr.io/tdk-soft/ergo-maffo-cloud-native/ergo-site=ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          kustomize build . > rendered-manifest.yaml

      # Manual Login (More reliable than the action for VPS setups)
      - name: Setup Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          # Set the env variable so the deploy action finds it automatically
          echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

      - name: Deploy to VPS
        uses: azure/k8s-deploy@v5
        with:
          action: deploy
          strategy: basic
          manifests: k8s/overlays/production/rendered-manifest.yaml
          namespace: ergo-prod